# Generated by Django 5.2.6 on 2025-09-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('boots', 'Football Boots'), ('ball', 'Football'), ('accessory', 'Accessories'), ('training', 'Training Equipment'), ('merch', 'Merchandise')], default='update', max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('item_views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
