# Generated by Django 5.2.6 on 2025-09-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField()),
                ('rating', models.IntegerField()),
                ('is_featured', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
