# Generated by Django 5.2.6 on 2025-09-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_views',
        ),
    ]
