# Generated by Django 5.2.6 on 2025-09-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_item_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
