# Generated by Django 5.2.6 on 2025-09-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_views',
            new_name='item_view',
        ),
    ]
