# Generated by Django 5.2.6 on 2025-09-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_item_views_product_item_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_view',
            new_name='item_views',
        ),
    ]
