# Generated by Django 5.2.6 on 2025-09-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_item_view_product_item_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_views',
        ),
    ]
